### ISSUE TITLE
When is this production ready?

### ISSUE THREAD

**Issue by zoomclub** [Famous/famous-react#7]
Glad to see that famous can be used with react, because react rocks! I'm looking to factor in famous only because it plays nice with react. When can I seriously start on that? What are the milestones I can count on?

**Comment by gojohnnygo** [comment]
@contra - Is mixed mode not out yet? I see demos of it on their blog (https://famo.us/blog/tag/mixed-mode/) but couldn't find a formal announcement of it.

**Comment by TheAlphaNerd** [comment]
@gojohnnygo Mixed Mode is not yet released.  We have been screening internal demos at demo day, but we have not released anything publicly yet.

The plan is to release Mixed Mode at the end of June along side the jQuerySF conference (which we are helping to plan)

**Comment by contra** [comment]
Please see https://github.com/Famous/famous-react/issues/10
