### ISSUE TITLE
can you please write an overview on how famous-react works?

### ISSUE THREAD

**Issue by netdur** [Famous/famous-react#9]
I have a lot of questions about everything, mainly about the benefits of famous-react integration, I am not sure how react's virtual DOM is used, which library does the writing to DOM, an brief overview will help a lot wrapping mind about this and contribute a bit

thanks

**Comment by RedCloudDC** [comment]
is this project pretty much D.O.A. or Famous-React come back to life in 2015?

**Comment by hannyajin** [comment]
@RedCloudDC @contra Wondering the same thing - any status updates?

**Comment by TheAlphaNerd** [comment]
This project is not going to be worked on again. If there is a Mixed Mode + React integration it will have to be started over again from scratch.
